# Site settings
title: DevOpsDays Portugal
description: June 3rd-4th, Lisbon, Portugal
email: organizers-portugal-2019@devopsdays.org
baseurl:
#url: "http://pranav.maangalabs.com" # the base hostname & protocol for your site
#favicon
favicon: /portodata-logo1.png

#feed
#feedburner_username: maangalabs
#twitter
twitter_username: devopsdayspt
github_username:  devopsdaysportugal

#linkedin
linkedin_username: pranavrajs

#google analytics
google_analytics_id : UA-53386152-2
#gplus
gplus_username: 101893920934936418705

#fb_username
#fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  eduardopiairo:
    display_name: DevOpsDays Portugal
    email: devopsdaysportugal@gmail.com
    linkedin: devopsdaysportugal
    twitter: devopsdayspt
    github: devopsdaysportugal
